### DISCUSSION TITLE
Empty structs for ConfigSync API

### DISCUSSION THREAD

**Discussion by mikebz** [GoogleContainerTools/kpt-config-sync#220] [Q&A] [answered]
If one was to import `pkg/api/configsync/v1beta1/gitconfig.go` and use that to generate config (which is what I am doing).  Printing out the object or marshaling it to JSON creates an object that looks like this:
```yaml
  apiVersion: configsync.gke.io/v1beta1
  kind: RootSync
  metadata:
    name: root-sync
    namespace: config-management-system
  spec:
    git:
      auth: none
      dir: /root-sync
      period: 0s
      privateCertSecret: {}
      repo: https://github.com/mikebz/kpt-samples.git/root-sync
      revision: v6
      secretRef: {}
    override: {}
    sourceType: git
```

The reason is because these structs are not declared as pointers:
```go
	SecretRef SecretReference `json:"secretRef,omitempty"`
...
	CACertSecretRef SecretReference `json:"caCertSecretRef,omitempty"`
```

Is there a reason for it?
