### DISCUSSION TITLE
ensure CRDs are installed first

### DISCUSSION THREAD

**Discussion by ajayyeluri** [GoogleContainerTools/kpt-config-sync#302] [Q&A] [answered]
I have been trying to get the config Sync working on AWS EKS.  
Using Version v1.13.0
When trying to register my git repo with on my cluster 
```yaml
apiVersion: configmanagement.gke.io/v1
#apiVersion: configsync.gke.io/v1beta1
kind: ConfigManagement
metadata:
  name: config-management
  namespace: config-management-system
spec:
  clusterName: my-cluster
  git:
    syncRepo: https://github.com/sidgs/hello-config-sync
    syncBranch: master
    secretType: none
    policyDir: "policy"
```

I keep getting the below error below 
no matches for kind "ConfigManagement" in version "configmanagement.gke.io/v1"

Help would be much appreciated
